name: Schedule Scraper

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 6 hours

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scraper on Vercel
        run: curl -X POST https://your-vercel-app.vercel.app/run_scraper