name: Schedule Scraper

on:
  push:   # Trigger on push events
    branches:
      - main
  schedule:  # Schedule trigger every 6 hours
    - cron: "0 */6 * * *"

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scraper on Vercel
        run: curl -X POST https://qubit-scraper-1p8gjut6x-nucleongodxs-projects.vercel.app/run_scraper