name: Schedule Scraper

on:
  push:   
    branches:
      - main
  schedule: 
    - cron: "0 */3 * * *"

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scraper 
        run: |
          curl -X POST https://qubit-scraper-amazing-systummm-ewjqy.onrender.com/run_scraper --silent --max-time 5